// Dados completos das cartas das coleções SV09 e SV10
// Baseado nos PDFs oficiais da Pokémon TCG

window.pokemonTypes = {
  grass: { name: 'Grama', icon: '🌿', color: '#78C850' },
  fire: { name: 'Fogo', icon: '🔥', color: '#F08030' },
  water: { name: 'Água', icon: '💧', color: '#6890F0' },
  electric: { name: 'Elétrico', icon: '⚡', color: '#F8D030' },
  psychic: { name: 'Psíquico', icon: '🔮', color: '#F85888' },
  fighting: { name: 'Lutador', icon: '🥊', color: '#C03028' },
  dark: { name: 'Sombrio', icon: '🌙', color: '#705848' },
  steel: { name: 'Aço', icon: '⚙️', color: '#B8B8D0' },
  fairy: { name: 'Fada', icon: '✨', color: '#EE99AC' },
  dragon: { name: 'Dragão', icon: '🐉', color: '#7038F8' },
  normal: { name: 'Normal', icon: '⭐', color: '#A8A878' }
};

window.rarityTypes = {
  common: { name: 'Comum', symbol: '●', color: '#000000' },
  uncommon: { name: 'Incomum', symbol: '◆', color: '#000000ff' },
  rare: { name: 'Rara', symbol: '★', color: '#000000ff' },
  doubleRare: { name: 'Rara Dupla', symbol: '★★', color: '#000000ff' },
  ultraRare: { name: 'Ultra Rara', symbol: '★★', color: '#ffa600ff' },
  illustrationRare: { name: 'Ilustração Rara', symbol: '★', color: '#8e17f0ff' },
  specialIllustration: { name: 'Ilustração Rara Especial', symbol: '★★', color: '#8e17f0ff' },
  hyperRare: { name: 'Hiper Rara', symbol: '★★★', color: '#ffa600ff' }
};

window.cardData = {
  journey: [
    { num: 1, name: 'Caterpie', type: 'grass', rarity: 'common' },
    { num: 2, name: 'Metapod', type: 'grass', rarity: 'common' },
    { num: 3, name: 'Butterfree', type: 'grass', rarity: 'uncommon' },
    { num: 4, name: 'Paras', type: 'grass', rarity: 'common' },
    { num: 5, name: 'Parasect', type: 'grass', rarity: 'uncommon' },
    { num: 6, name: 'Petilil', type: 'grass', rarity: 'common' },
    { num: 7, name: 'Lilligant', type: 'grass', rarity: 'uncommon' },
    { num: 8, name: 'Maractus', type: 'grass', rarity: 'common' },
    { num: 9, name: 'Karrablast', type: 'grass', rarity: 'common' },
    { num: 10, name: 'Foongus', type: 'grass', rarity: 'common' },
    { num: 11, name: 'Amoonguss ex', type: 'grass', rarity: 'doubleRare' },
    { num: 12, name: 'Shelmet', type: 'grass', rarity: 'common' },
    { num: 13, name: 'Accelgor', type: 'grass', rarity: 'uncommon' },
    { num: 14, name: 'Durant', type: 'grass', rarity: 'common' },
    { num: 15, name: 'Virizion', type: 'grass', rarity: 'rare' },
    { num: 16, name: 'Sprigatito', type: 'grass', rarity: 'common' },
    { num: 17, name: 'Floragato', type: 'grass', rarity: 'uncommon' },
    { num: 18, name: 'Meowscarada', type: 'grass', rarity: 'rare' },
    { num: 19, name: 'Nymble', type: 'grass', rarity: 'common' },
    { num: 20, name: 'Magmar', type: 'fire', rarity: 'common' },
    { num: 21, name: 'Magmortar', type: 'fire', rarity: 'uncommon' },
    { num: 22, name: 'Torchic', type: 'fire', rarity: 'common' },
    { num: 23, name: 'Combusken', type: 'fire', rarity: 'uncommon' },
    { num: 24, name: 'Blaziken ex', type: 'fire', rarity: 'doubleRare' },
    { num: 25, name: 'Torkoal', type: 'fire', rarity: 'common' },
    { num: 26, name: 'Darumaka do N', type: 'fire', rarity: 'common' },
    { num: 27, name: 'Darmanitan do N', type: 'fire', rarity: 'uncommon' },
    { num: 28, name: 'Larvesta', type: 'fire', rarity: 'common' },
    { num: 29, name: 'Volcarona', type: 'fire', rarity: 'rare' },
    { num: 30, name: 'Reshiram ex', type: 'fire', rarity: 'doubleRare' },
    { num: 31, name: 'Volcanion ex', type: 'fire', rarity: 'doubleRare' },
    { num: 32, name: 'Articuno', type: 'water', rarity: 'rare' },
    { num: 33, name: 'Remoraid', type: 'water', rarity: 'common' },
    { num: 34, name: 'Octillery', type: 'water', rarity: 'uncommon' },
    { num: 35, name: 'Lotad', type: 'water', rarity: 'common' },
    { num: 36, name: 'Lombre', type: 'water', rarity: 'uncommon' },
    { num: 37, name: 'Ludicolo', type: 'water', rarity: 'rare' },
    { num: 38, name: 'Wingull', type: 'water', rarity: 'common' },
    { num: 39, name: 'Pelipper', type: 'water', rarity: 'uncommon' },
    { num: 40, name: 'Wailmer', type: 'water', rarity: 'common' },
    { num: 41, name: 'Wailord', type: 'water', rarity: 'uncommon' },
    { num: 42, name: 'Regice', type: 'water', rarity: 'rare' },
    { num: 43, name: 'Veluza ex', type: 'water', rarity: 'doubleRare' },
    { num: 44, name: 'Geodude de Alola', type: 'electric', rarity: 'common' },
    { num: 45, name: 'Graveler de Alola', type: 'electric', rarity: 'uncommon' },
    { num: 46, name: 'Golem de Alola', type: 'electric', rarity: 'rare' },
    { num: 47, name: 'Voltorb da Iono', type: 'electric', rarity: 'common' },
    { num: 48, name: 'Electrode da Iono', type: 'electric', rarity: 'uncommon' },
    { num: 49, name: 'Joltik do N', type: 'electric', rarity: 'common' },
    { num: 50, name: 'Togedemaru', type: 'electric', rarity: 'common' },
    { num: 51, name: 'Tapu Koko ex', type: 'electric', rarity: 'doubleRare' },
    { num: 52, name: 'Tadbulb da Iono', type: 'electric', rarity: 'common' },
    { num: 53, name: 'Bellibolt ex da Iono', type: 'electric', rarity: 'ultraRare' },
    { num: 54, name: 'Wattrel da Iono', type: 'electric', rarity: 'common' },
    { num: 55, name: 'Kilowattrel da Iono', type: 'electric', rarity: 'uncommon' },
    { num: 56, name: 'Clefairy ex da Lillie', type: 'psychic', rarity: 'ultraRare' },
    { num: 57, name: 'Marowak de Alola', type: 'psychic', rarity: 'uncommon' },
    { num: 58, name: 'Mr. Mime', type: 'psychic', rarity: 'common' },
    { num: 59, name: 'Shuppet', type: 'psychic', rarity: 'common' },
    { num: 60, name: 'Banette', type: 'psychic', rarity: 'uncommon' },
    { num: 61, name: 'Beldum', type: 'psychic', rarity: 'common' },
    { num: 62, name: 'Metang', type: 'psychic', rarity: 'uncommon' },
    { num: 63, name: 'Metagross', type: 'psychic', rarity: 'rare' },
    { num: 64, name: 'Sigilyph do N', type: 'psychic', rarity: 'uncommon' },
    { num: 65, name: 'Oricorio', type: 'psychic', rarity: 'uncommon' },
    { num: 66, name: 'Cutiefly da Lillie', type: 'psychic', rarity: 'common' },
    { num: 67, name: 'Ribombee da Lillie', type: 'psychic', rarity: 'uncommon' },
    { num: 68, name: 'Comfey da Lillie', type: 'psychic', rarity: 'uncommon' },
    { num: 69, name: 'Mimikyu ex', type: 'psychic', rarity: 'doubleRare' },
    { num: 70, name: 'Dhelmise', type: 'psychic', rarity: 'uncommon' },
    { num: 71, name: 'Impidimp', type: 'psychic', rarity: 'common' },
    { num: 72, name: 'Morgrem', type: 'psychic', rarity: 'uncommon' },
    { num: 73, name: 'Grimmsnarl', type: 'psychic', rarity: 'rare' },
    { num: 74, name: 'Milcery', type: 'psychic', rarity: 'common' },
    { num: 75, name: 'Alcremie ex', type: 'psychic', rarity: 'doubleRare' },
    { num: 76, name: 'Cubone', type: 'fighting', rarity: 'common' },
    { num: 77, name: 'Swinub', type: 'fighting', rarity: 'common' },
    { num: 78, name: 'Piloswine', type: 'fighting', rarity: 'uncommon' },
    { num: 79, name: 'Mamoswine ex', type: 'fighting', rarity: 'doubleRare' },
    { num: 80, name: 'Larvitar', type: 'fighting', rarity: 'common' },
    { num: 81, name: 'Pupitar', type: 'fighting', rarity: 'uncommon' },
    { num: 82, name: 'Regirock', type: 'fighting', rarity: 'rare' },
    { num: 83, name: 'Pancham', type: 'fighting', rarity: 'common' },
    { num: 84, name: 'Rockruff', type: 'fighting', rarity: 'common' },
    { num: 85, name: 'Lycanroc', type: 'fighting', rarity: 'uncommon' },
    { num: 86, name: 'Silicobra do Hop', type: 'fighting', rarity: 'common' },
    { num: 87, name: 'Sandaconda do Hop', type: 'fighting', rarity: 'uncommon' },
    { num: 88, name: 'Toedscool', type: 'fighting', rarity: 'common' },
    { num: 89, name: 'Toedscruel', type: 'fighting', rarity: 'uncommon' },
    { num: 90, name: 'Klawf', type: 'fighting', rarity: 'uncommon' },
    { num: 91, name: 'Koffing', type: 'fighting', rarity: 'common' },
    { num: 92, name: 'Weezing', type: 'fighting', rarity: 'uncommon' },
    { num: 93, name: 'Wooper de Paldea', type: 'fighting', rarity: 'common' },
    { num: 94, name: 'Clodsire de Paldea ex', type: 'fighting', rarity: 'doubleRare' },
    { num: 95, name: 'Tyranitar', type: 'dark', rarity: 'rare' },
    { num: 96, name: 'Purrloin do N', type: 'dark', rarity: 'common' },
    { num: 97, name: 'Zorua do N', type: 'dark', rarity: 'common' },
    { num: 98, name: 'Zoroark ex do N', type: 'dark', rarity: 'ultraRare' },
    { num: 99, name: 'Pangoro', type: 'dark', rarity: 'uncommon' },
    { num: 100, name: 'Lokix', type: 'dark', rarity: 'uncommon' },
    { num: 101, name: 'Bombirdier', type: 'dark', rarity: 'uncommon' },
    { num: 102, name: 'Escavalier', type: 'steel', rarity: 'uncommon' },
    { num: 103, name: 'Klink do N', type: 'steel', rarity: 'common' },
    { num: 104, name: 'Klang do N', type: 'steel', rarity: 'uncommon' },
    { num: 105, name: 'Klinklang do N', type: 'steel', rarity: 'rare' },
    { num: 106, name: 'Stunfisk de Galar', type: 'steel', rarity: 'uncommon' },
    { num: 107, name: 'Magearna', type: 'steel', rarity: 'rare' },
    { num: 108, name: 'Corviknight do Hop', type: 'steel', rarity: 'uncommon' },
    { num: 109, name: 'Cufant', type: 'steel', rarity: 'common' },
    { num: 110, name: 'Copperajah', type: 'steel', rarity: 'uncommon' },
    { num: 111, name: 'Zacian ex do Hop', type: 'steel', rarity: 'ultraRare' },
    { num: 112, name: 'Bagon', type: 'dragon', rarity: 'common' },
    { num: 113, name: 'Shelgon', type: 'dragon', rarity: 'uncommon' },
    { num: 114, name: 'Salamence ex', type: 'dragon', rarity: 'doubleRare' },
    { num: 115, name: 'Druddigon', type: 'dragon', rarity: 'uncommon' },
    { num: 116, name: 'Reshiram do N', type: 'dragon', rarity: 'uncommon' },
    { num: 117, name: 'Snorlax do Hop', type: '	normal', rarity: 'uncommon' },
    { num: 118, name: 'Sentret', type: '	normal', rarity: 'common' },
    { num: 119, name: 'Furret', type: '	normal', rarity: 'uncommon' },
    { num: 120, name: 'Dunsparce', type: '	normal', rarity: 'common' },
    { num: 121, name: 'Dudunsparce ex', type: '	normal', rarity: 'doubleRare' },
    { num: 122, name: 'Kecleon', type: '	normal', rarity: 'uncommon' },
    { num: 123, name: 'Tropius', type: '	normal', rarity: 'uncommon' },
    { num: 124, name: 'Audino', type: '	normal', rarity: 'uncommon' },
    { num: 125, name: 'Minccino', type: '	normal', rarity: 'common' },
    { num: 126, name: 'Cinccino', type: '	normal', rarity: 'uncommon' },
    { num: 127, name: 'Noibat', type: '	normal', rarity: 'common' },
    { num: 128, name: 'Noivern', type: '	normal', rarity: 'uncommon' },
    { num: 129, name: 'Komala', type: '	normal', rarity: 'uncommon' },
    { num: 130, name: 'Drampa', type: '	normal', rarity: 'uncommon' },
    { num: 131, name: 'Skwovet', type: '	normal', rarity: 'common' },
    { num: 132, name: 'Greedent', type: '	normal', rarity: 'uncommon' },
    { num: 133, name: 'Rookidee do Hop', type: '	normal', rarity: 'common' },
    { num: 134, name: 'Corvisquire do Hop', type: '	normal', rarity: 'uncommon' },
    { num: 135, name: 'Wooloo do Hop', type: '	normal', rarity: 'common' },
    { num: 136, name: 'Dubwool do Hop', type: '	normal', rarity: 'uncommon' },
    { num: 137, name: 'Cramorant', type: '	normal', rarity: 'uncommon' },
    { num: 138, name: 'Cramorant do Hop', type: '	normal', rarity: 'uncommon' },
    { num: 139, name: 'Lechonk', type: '	normal', rarity: 'common' },
    { num: 140, name: 'Oinkologne', type: '	normal', rarity: 'uncommon' },
    { num: 141, name: 'Squawkabilly', type: '	normal', rarity: 'uncommon' },
    { num: 142, name: 'Avery e Klara', type: '	normal', rarity: 'uncommon' },
    { num: 143, name: 'Treino de Faixa Preta', type: '	normal', rarity: 'uncommon' },
    { num: 144, name: 'Treino de Faixa Preta', type: '	normal', rarity: 'uncommon' },
    { num: 145, name: 'Treino de Faixa Preta', type: '	normal', rarity: 'uncommon' },
    { num: 146, name: 'Busca do Brock', type: '	normal', rarity: 'uncommon' },
    { num: 147, name: 'Bolsa do Hop', type: '	normal', rarity: 'uncommon' },
    { num: 148, name: 'Faixa da Escolha do Hop', type: '	normal', rarity: 'uncommon' },
    { num: 149, name: 'Espírito de Luta da Iris', type: '	normal', rarity: 'uncommon' },
    { num: 150, name: 'Levincia', type: '	normal', rarity: 'uncommon' },
    { num: 151, name: 'Pérola da Lillie', type: '	normal', rarity: 'uncommon' },
    { num: 152, name: 'Castelo do N', type: '	normal', rarity: 'uncommon' },
    { num: 153, name: 'PP Up do N', type: '	normal', rarity: 'uncommon' },
    { num: 154, name: 'Postwick', type: '	normal', rarity: 'uncommon' },
    { num: 155, name: 'Pesquisa de Professores', type: '	normal', rarity: 'uncommon' },
    { num: 156, name: 'Ingresso Resgatável', type: '	normal', rarity: 'uncommon' },
    { num: 157, name: 'Baderneiro', type: '	normal', rarity: 'uncommon' },
    { num: 158, name: 'Superpoção', type: '	normal', rarity: 'uncommon' },
    { num: 159, name: 'Energia Espinhosa', type: '	normal', rarity: 'uncommon' },
    { num: 160, name: 'Maractus', type: 'grass', rarity: 'illustrationRare' },
    { num: 161, name: 'Articuno', type: 'water', rarity: 'illustrationRare' },
    { num: 162, name: 'Wailord', type: 'water', rarity: 'illustrationRare' },
    { num: 163, name: 'Kilowattrel da Iono', type: 'electric', rarity: 'illustrationRare' },
    { num: 164, name: 'Ribombee da Lillie', type: 'psychic', rarity: 'illustrationRare' },
    { num: 165, name: 'Swinub', type: 'fighting', rarity: 'illustrationRare' },
    { num: 166, name: 'Lycanroc', type: 'fighting', rarity: 'illustrationRare' },
    { num: 167, name: 'Reshiram do N', type: 'dragon', rarity: 'illustrationRare' },
    { num: 168, name: 'Furret', type: '	normal', rarity: 'illustrationRare' },
    { num: 169, name: 'Noibat', type: '	normal', rarity: 'illustrationRare' },
    { num: 170, name: 'Wooloo do Hop', type: '	normal', rarity: 'illustrationRare' },
    { num: 171, name: 'Volcanion ex', type: 'fire', rarity: 'specialIllustration' },
    { num: 172, name: 'Bellibolt ex da Iono', type: 'electric', rarity: 'specialIllustration' },
    { num: 173, name: 'Clefairy ex da Lillie', type: 'psychic', rarity: 'specialIllustration' },
    { num: 174, name: 'Mamoswine ex', type: 'fighting', rarity: 'specialIllustration' },
    { num: 175, name: 'Zoroark ex do N', type: 'dark', rarity: 'specialIllustration' },
    { num: 176, name: 'Zacian ex do Hop', type: 'steel', rarity: 'specialIllustration' },
    { num: 177, name: 'Salamence ex', type: 'dragon', rarity: 'specialIllustration' },
    { num: 178, name: 'Dudunsparce ex', type: '	normal', rarity: 'specialIllustration' },
    { num: 179, name: 'Busca do Brock', type: '	normal', rarity: 'ultraRare' },
    { num: 180, name: 'Espírito de Luta da Iris', type: '	normal', rarity: 'ultraRare' },
    { num: 181, name: 'Baderneiro', type: '	normal', rarity: 'ultraRare' },
    { num: 182, name: 'Volcanion ex', type: 'fire', rarity: 'hyperRare' },
    { num: 183, name: 'Bellibolt ex da Iono', type: 'electric', rarity: 'hyperRare' },
    { num: 184, name: 'Clefairy ex da Lillie', type: 'psychic', rarity: 'hyperRare' },
    { num: 185, name: 'Zoroark ex do N', type: 'dark', rarity: 'hyperRare' },
    { num: 186, name: 'Zacian ex do Hop', type: 'steel', rarity: 'hyperRare' },
    { num: 187, name: 'Salamence ex', type: 'dragon', rarity: 'hyperRare' },
    { num: 188, name: 'Bellibolt ex da Iono', type: 'electric', rarity: 'hyperRare' },
    { num: 189, name: 'Zoroark ex do N', type: 'dark', rarity: 'hyperRare' },
    { num: 190, name: 'Energia Espinhosa', type: '	normal', rarity: 'hyperRare' }
  ],
  rivals: [
    { num: 1, name: 'Pinsir do Ethan', type: 'grass', rarity: 'uncommon' },
    { num: 2, name: 'Yanma', type: 'grass', rarity: 'common' },
    { num: 3, name: 'Yanmega ex', type: 'grass', rarity: 'doubleRare' },
    { num: 4, name: 'Pineco', type: 'grass', rarity: 'common' },
    { num: 5, name: 'Shroomish', type: 'grass', rarity: 'common' },
    { num: 6, name: 'Breloom', type: 'grass', rarity: 'uncommon' },
    { num: 7, name: 'Roselia da Cynthia', type: 'grass', rarity: 'common' },
    { num: 8, name: 'Roserade da Cynthia', type: 'grass', rarity: 'rare' },
    { num: 9, name: 'Mow Rotom', type: 'grass', rarity: 'common' },
    { num: 10, name: 'Shaymin', type: 'grass', rarity: 'uncommon' },
    { num: 11, name: 'Dwebble', type: 'grass', rarity: 'common' },
    { num: 12, name: 'Crustle', type: 'grass', rarity: 'uncommon' },
    { num: 13, name: 'Fomantis', type: 'grass', rarity: 'common' },
    { num: 14, name: 'Lurantis', type: 'grass', rarity: 'uncommon' },
    { num: 15, name: 'Blipbug da Team Rocket', type: 'grass', rarity: 'common' },
    { num: 16, name: 'Applin', type: 'grass', rarity: 'common' },
    { num: 17, name: 'Dipplin', type: 'grass', rarity: 'uncommon' },
    { num: 18, name: 'Hydrapple', type: 'grass', rarity: 'rare' },
    { num: 19, name: 'Tarountula da Team Rocket', type: 'grass', rarity: 'common' },
    { num: 20, name: 'Spidops da Team Rocket', type: 'grass', rarity: 'uncommon' },
    { num: 21, name: 'Smoliv', type: 'grass', rarity: 'common' },
    { num: 22, name: 'Dolliv', type: 'grass', rarity: 'common' },
    { num: 23, name: 'Arboliva', type: 'grass', rarity: 'uncommon' },
    { num: 24, name: 'Bramblin', type: 'grass', rarity: 'common' },
    { num: 25, name: 'Brambleghast', type: 'grass', rarity: 'uncommon' },
    { num: 26, name: 'Toedscool', type: 'grass', rarity: 'common' },
    { num: 27, name: 'Vulpix de Alola', type: 'fire', rarity: 'common' },
    { num: 28, name: 'Ninetales de Alola', type: 'fire', rarity: 'uncommon' },
    { num: 29, name: 'Growlithe da Marnie', type: 'fire', rarity: 'common' },
    { num: 30, name: 'Arcanine da Marnie', type: 'fire', rarity: 'uncommon' },
    { num: 31, name: 'Entei', type: 'fire', rarity: 'rare' },
    { num: 32, name: 'Ho-Oh ex do Ethan', type: 'fire', rarity: 'ultraRare' },
    { num: 33, name: 'Magby', type: 'fire', rarity: 'common' },
    { num: 34, name: 'Magmar', type: 'fire', rarity: 'uncommon' },
    { num: 35, name: 'Magmortar ex', type: 'fire', rarity: 'doubleRare' },
    { num: 36, name: 'Heatmor', type: 'fire', rarity: 'uncommon' },
    { num: 37, name: 'Fletchling', type: 'fire', rarity: 'common' },
    { num: 38, name: 'Fletchinder', type: 'fire', rarity: 'uncommon' },
    { num: 39, name: 'Talonflame', type: 'fire', rarity: 'rare' },
    { num: 40, name: 'Litleo', type: 'fire', rarity: 'common' },
    { num: 41, name: 'Pyroar', type: 'fire', rarity: 'uncommon' },
    { num: 42, name: 'Fuecoco', type: 'fire', rarity: 'common' },
    { num: 43, name: 'Crocalor', type: 'fire', rarity: 'uncommon' },
    { num: 44, name: 'Skeledirge', type: 'fire', rarity: 'rare' },
    { num: 45, name: 'Charcadet', type: 'fire', rarity: 'common' },
    { num: 46, name: 'Armarouge', type: 'fire', rarity: 'uncommon' },
    { num: 47, name: 'Magikarp da Misty', type: 'water', rarity: 'common' },
    { num: 48, name: 'Gyarados da Misty', type: 'water', rarity: 'uncommon' },
    { num: 49, name: 'Lapras', type: 'water', rarity: 'uncommon' },
    { num: 50, name: 'Politoed da Misty', type: 'water', rarity: 'uncommon' },
    { num: 51, name: 'Suicune', type: 'water', rarity: 'rare' },
    { num: 52, name: 'Totodile do Ethan', type: 'water', rarity: 'common' },
    { num: 53, name: 'Croconaw do Ethan', type: 'water', rarity: 'uncommon' },
    { num: 54, name: 'Feraligatr do Ethan', type: 'water', rarity: 'rare' },
    { num: 55, name: 'Lotad', type: 'water', rarity: 'common' },
    { num: 56, name: 'Lombre', type: 'water', rarity: 'uncommon' },
    { num: 57, name: 'Ludicolo', type: 'water', rarity: 'rare' },
    { num: 58, name: 'Feebas', type: 'water', rarity: 'common' },
    { num: 59, name: 'Milotic da Cynthia', type: 'water', rarity: 'uncommon' },
    { num: 60, name: 'Shellos', type: 'water', rarity: 'common' },
    { num: 61, name: 'Gastrodon da Cynthia', type: 'water', rarity: 'uncommon' },
    { num: 62, name: 'Finneon', type: 'water', rarity: 'common' },
    { num: 63, name: 'Lumineon', type: 'water', rarity: 'uncommon' },
    { num: 64, name: 'Tympole', type: 'water', rarity: 'common' },
    { num: 65, name: 'Palpitoad', type: 'water', rarity: 'uncommon' },
    { num: 66, name: 'Seismitoad', type: 'water', rarity: 'rare' },
    { num: 67, name: 'Froakie', type: 'water', rarity: 'common' },
    { num: 68, name: 'Frogadier', type: 'water', rarity: 'uncommon' },
    { num: 69, name: 'Greninja', type: 'water', rarity: 'rare' },
    { num: 70, name: 'Arrokuda', type: 'water', rarity: 'common' },
    { num: 71, name: 'Barraskewda', type: 'water', rarity: 'uncommon' },
    { num: 72, name: 'Dondozo', type: 'water', rarity: 'uncommon' },
    { num: 73, name: 'Pikachu da Misty', type: 'electric', rarity: 'common' },
    { num: 74, name: 'Raichu da Misty', type: 'electric', rarity: 'uncommon' },
    { num: 75, name: 'Raikou', type: 'electric', rarity: 'rare' },
    { num: 76, name: 'Plusle', type: 'electric', rarity: 'common' },
    { num: 77, name: 'Minun', type: 'electric', rarity: 'common' },
    { num: 78, name: 'Shinx', type: 'electric', rarity: 'common' },
    { num: 79, name: 'Luxio', type: 'electric', rarity: 'uncommon' },
    { num: 80, name: 'Luxray', type: 'electric', rarity: 'rare' },
    { num: 81, name: 'Blitzle', type: 'electric', rarity: 'common' },
    { num: 82, name: 'Zebstrika', type: 'electric', rarity: 'uncommon' },
    { num: 83, name: 'Tadbulb', type: 'electric', rarity: 'common' },
    { num: 84, name: 'Bellibolt', type: 'electric', rarity: 'uncommon' },
    { num: 85, name: 'Toxel', type: 'electric', rarity: 'common' },
    { num: 86, name: 'Toxtricity', type: 'electric', rarity: 'uncommon' },
    { num: 87, name: 'Pawmi', type: 'electric', rarity: 'common' },
    { num: 88, name: 'Pawmo', type: 'electric', rarity: 'uncommon' },
    { num: 89, name: 'Pawmot', type: 'electric', rarity: 'rare' },
    { num: 90, name: 'Grimer de Alola', type: 'psychic', rarity: 'common' },
    { num: 91, name: 'Muk de Alola', type: 'psychic', rarity: 'uncommon' },
    { num: 92, name: 'Misdreavus', type: 'psychic', rarity: 'common' },
    { num: 93, name: 'Mismagius', type: 'psychic', rarity: 'uncommon' },
    { num: 94, name: 'Ralts', type: 'psychic', rarity: 'common' },
    { num: 95, name: 'Kirlia', type: 'psychic', rarity: 'uncommon' },
    { num: 96, name: 'Gardevoir', type: 'psychic', rarity: 'rare' },
    { num: 97, name: 'Spoink da Cynthia', type: 'psychic', rarity: 'common' },
    { num: 98, name: 'Grumpig da Cynthia', type: 'psychic', rarity: 'uncommon' },
    { num: 99, name: 'Chimecho', type: 'psychic', rarity: 'uncommon' },
    { num: 100, name: 'Gothita', type: 'psychic', rarity: 'common' },
    { num: 101, name: 'Gothorita', type: 'psychic', rarity: 'uncommon' },
    { num: 102, name: 'Gothitelle', type: 'psychic', rarity: 'rare' },
    { num: 103, name: 'Dedenne', type: 'psychic', rarity: 'uncommon' },
    { num: 104, name: 'Flabébé', type: 'psychic', rarity: 'common' },
    { num: 105, name: 'Floette', type: 'psychic', rarity: 'uncommon' },
    { num: 106, name: 'Florges', type: 'psychic', rarity: 'rare' },
    { num: 107, name: 'Morgrem da Marnie', type: 'psychic', rarity: 'uncommon' },
    { num: 108, name: 'Grimmsnarl da Marnie', type: 'psychic', rarity: 'rare' },
    { num: 109, name: 'Hatenna', type: 'psychic', rarity: 'common' },
    { num: 110, name: 'Hattrem', type: 'psychic', rarity: 'uncommon' },
    { num: 111, name: 'Hatterene', type: 'psychic', rarity: 'rare' },
    { num: 112, name: 'Tinkatink', type: 'psychic', rarity: 'common' },
    { num: 113, name: 'Tinkatuff', type: 'psychic', rarity: 'uncommon' },
    { num: 114, name: 'Tinkaton', type: 'psychic', rarity: 'rare' },
    { num: 115, name: 'Screamtail', type: 'psychic', rarity: 'uncommon' },
    { num: 116, name: 'Flutter Mane', type: 'psychic', rarity: 'rare' },
    { num: 117, name: 'Machop', type: 'fighting', rarity: 'common' },
    { num: 118, name: 'Machoke', type: 'fighting', rarity: 'uncommon' },
    { num: 119, name: 'Machamp ex', type: 'fighting', rarity: 'doubleRare' },
    { num: 120, name: 'Tyrogue', type: 'fighting', rarity: 'common' },
    { num: 121, name: 'Hitmontop', type: 'fighting', rarity: 'uncommon' },
    { num: 122, name: 'Makuhita', type: 'fighting', rarity: 'common' },
    { num: 123, name: 'Hariyama', type: 'fighting', rarity: 'uncommon' },
    { num: 124, name: 'Riolu', type: 'fighting', rarity: 'common' },
    { num: 125, name: 'Lucario da Cynthia', type: 'fighting', rarity: 'uncommon' },
    { num: 126, name: 'Croagunk', type: 'fighting', rarity: 'common' },
    { num: 127, name: 'Toxicroak', type: 'fighting', rarity: 'uncommon' },
    { num: 128, name: 'Roggenrola', type: 'fighting', rarity: 'common' },
    { num: 129, name: 'Boldore', type: 'fighting', rarity: 'uncommon' },
    { num: 130, name: 'Gigalith', type: 'fighting', rarity: 'rare' },
    { num: 131, name: 'Throh', type: 'fighting', rarity: 'uncommon' },
    { num: 132, name: 'Sawk', type: 'fighting', rarity: 'uncommon' },
    { num: 133, name: 'Mienfoo', type: 'fighting', rarity: 'common' },
    { num: 134, name: 'Mienshao', type: 'fighting', rarity: 'uncommon' },
    { num: 135, name: 'Hawlucha', type: 'fighting', rarity: 'uncommon' },
    { num: 136, name: 'Crabrawler', type: 'fighting', rarity: 'common' },
    { num: 137, name: 'Crabominable', type: 'fighting', rarity: 'uncommon' },
    { num: 138, name: 'Nacli', type: 'fighting', rarity: 'common' },
    { num: 139, name: 'Naclstack', type: 'fighting', rarity: 'uncommon' },
    { num: 140, name: 'Garganacl', type: 'fighting', rarity: 'rare' },
    { num: 141, name: 'Iron Hands', type: 'fighting', rarity: 'rare' },
    { num: 142, name: 'Ekans da Team Rocket', type: 'dark', rarity: 'common' },
    { num: 143, name: 'Arbok da Team Rocket', type: 'dark', rarity: 'uncommon' },
    { num: 144, name: 'Koffing da Team Rocket', type: 'dark', rarity: 'common' },
    { num: 145, name: 'Weezing da Team Rocket', type: 'dark', rarity: 'uncommon' },
    { num: 146, name: 'Mewtwo ex da Team Rocket', type: 'dark', rarity: 'ultraRare' },
    { num: 147, name: 'Umbreon', type: 'dark', rarity: 'uncommon' },
    { num: 148, name: 'Murkrow', type: 'dark', rarity: 'common' },
    { num: 149, name: 'Honchkrow', type: 'dark', rarity: 'uncommon' },
    { num: 150, name: 'Poochyena', type: 'dark', rarity: 'common' },
    { num: 151, name: 'Mightyena', type: 'dark', rarity: 'uncommon' },
    { num: 152, name: 'Spiritomb da Cynthia', type: 'dark', rarity: 'uncommon' },
    { num: 153, name: 'Purrloin', type: 'dark', rarity: 'common' },
    { num: 154, name: 'Liepard', type: 'dark', rarity: 'uncommon' },
    { num: 155, name: 'Zorua', type: 'dark', rarity: 'common' },
    { num: 156, name: 'Zoroark', type: 'dark', rarity: 'uncommon' },
    { num: 157, name: 'Vullaby', type: 'dark', rarity: 'common' },
    { num: 158, name: 'Mandibuzz', type: 'dark', rarity: 'uncommon' },
    { num: 159, name: 'Morpeko da Marnie', type: 'dark', rarity: 'uncommon' },
    { num: 160, name: 'Maschiff do Arven', type: 'dark', rarity: 'common' },
    { num: 161, name: 'Mabosstiff ex do Arven', type: 'dark', rarity: 'ultraRare' },
    { num: 162, name: 'Psyduck da Misty', type: 'steel', rarity: 'common' },
    { num: 163, name: 'Golduck da Misty', type: 'steel', rarity: 'uncommon' },
    { num: 164, name: 'Magnemite', type: 'steel', rarity: 'common' },
    { num: 165, name: 'Magneton', type: 'steel', rarity: 'uncommon' },
    { num: 166, name: 'Magnezone', type: 'steel', rarity: 'rare' },
    { num: 167, name: 'steelix do Steven', type: 'steel', rarity: 'uncommon' },
    { num: 168, name: 'Skarmory', type: 'steel', rarity: 'uncommon' },
    { num: 169, name: 'Metang do Steven', type: 'steel', rarity: 'uncommon' },
    { num: 170, name: 'Metagross do Steven', type: 'steel', rarity: 'rare' },
    { num: 171, name: 'Jirachi', type: 'steel', rarity: 'rare' },
    { num: 172, name: 'Shieldon', type: 'steel', rarity: 'common' },
    { num: 173, name: 'Bastiodon', type: 'steel', rarity: 'uncommon' },
    { num: 174, name: 'Bronzor da Cynthia', type: 'steel', rarity: 'common' },
    { num: 175, name: 'Bronzong da Cynthia', type: 'steel', rarity: 'uncommon' },
    { num: 176, name: 'Klink', type: 'steel', rarity: 'common' },
    { num: 177, name: 'Klang', type: 'steel', rarity: 'uncommon' },
    { num: 178, name: 'Klinklang', type: 'steel', rarity: 'rare' },
    { num: 179, name: 'Honedge', type: 'steel', rarity: 'common' },
    { num: 180, name: 'Doublade', type: 'steel', rarity: 'uncommon' },
    { num: 181, name: 'Aegislash', type: 'steel', rarity: 'rare' },
    { num: 182, name: 'Togedemaru', type: 'steel', rarity: 'uncommon' },
    { num: 183, name: 'Dratini', type: 'dragon', rarity: 'common' },
    { num: 184, name: 'Dragonair', type: 'dragon', rarity: 'uncommon' },
    { num: 185, name: 'Dragonite', type: 'dragon', rarity: 'rare' },
    { num: 186, name: 'Bagon da Cynthia', type: 'dragon', rarity: 'common' },
    { num: 187, name: 'Shelgon da Cynthia', type: 'dragon', rarity: 'uncommon' },
    { num: 188, name: 'Garchomp ex da Cynthia', type: 'dragon', rarity: 'ultraRare' },
    { num: 189, name: 'Axew', type: 'dragon', rarity: 'common' },
    { num: 190, name: 'Fraxure', type: 'dragon', rarity: 'uncommon' },
    { num: 191, name: 'Haxorus', type: 'dragon', rarity: 'rare' },
    { num: 192, name: 'Druddigon', type: 'dragon', rarity: 'uncommon' },
    { num: 193, name: 'Goomy', type: 'dragon', rarity: 'common' },
    { num: 194, name: 'Sliggoo', type: 'dragon', rarity: 'uncommon' },
    { num: 195, name: 'Goodra', type: 'dragon', rarity: 'rare' },
    { num: 196, name: 'Noibat', type: 'dragon', rarity: 'common' },
    { num: 197, name: 'Noivern', type: 'dragon', rarity: 'uncommon' },
    { num: 198, name: 'Applin', type: 'dragon', rarity: 'common' },
    { num: 199, name: 'Flapple', type: 'dragon', rarity: 'uncommon' },
    { num: 200, name: 'Frigibax', type: 'dragon', rarity: 'common' },
    { num: 201, name: 'Arctibax', type: 'dragon', rarity: 'uncommon' },
    { num: 202, name: 'Baxcalibur', type: 'dragon', rarity: 'rare' },
    { num: 203, name: 'Ditto', type: '	normal', rarity: 'uncommon' },
    { num: 204, name: 'Eevee', type: '	normal', rarity: 'common' },
    { num: 205, name: 'Porygon', type: '	normal', rarity: 'common' },
    { num: 206, name: 'Porygon2', type: '	normal', rarity: 'uncommon' },
    { num: 207, name: 'Porygon-Z', type: '	normal', rarity: 'rare' },
    { num: 208, name: 'Sentret', type: '	normal', rarity: 'common' },
    { num: 209, name: 'Furret', type: '	normal', rarity: 'uncommon' },
    { num: 210, name: 'Hoothoot', type: '	normal', rarity: 'common' },
    { num: 211, name: 'Noctowl', type: '	normal', rarity: 'uncommon' },
    { num: 212, name: 'Togetic da Cynthia', type: '	normal', rarity: 'uncommon' },
    { num: 213, name: 'Togekiss da Cynthia', type: '	normal', rarity: 'rare' },
    { num: 214, name: 'Starly', type: '	normal', rarity: 'common' },
    { num: 215, name: 'Staravia', type: '	normal', rarity: 'uncommon' },
    { num: 216, name: 'Staraptor', type: '	normal', rarity: 'rare' },
    { num: 217, name: 'Bidoof', type: '	normal', rarity: 'common' },
    { num: 218, name: 'Bibarel', type: '	normal', rarity: 'uncommon' },
    { num: 219, name: 'Patrat', type: '	normal', rarity: 'common' },
    { num: 220, name: 'Watchog', type: '	normal', rarity: 'uncommon' },
    { num: 221, name: 'Minccino', type: '	normal', rarity: 'common' },
    { num: 222, name: 'Cinccino', type: '	normal', rarity: 'uncommon' },
    { num: 223, name: 'Rufflet', type: '	normal', rarity: 'common' },
    { num: 224, name: 'Braviary', type: '	normal', rarity: 'uncommon' },
    { num: 225, name: 'Skwovet', type: '	normal', rarity: 'common' },
    { num: 226, name: 'Greedent', type: '	normal', rarity: 'uncommon' },
    { num: 227, name: 'Lechonk', type: '	normal', rarity: 'common' },
    { num: 228, name: 'Oinkologne', type: '	normal', rarity: 'uncommon' },
    { num: 229, name: 'Tandemaus', type: '	normal', rarity: 'common' },
    { num: 230, name: 'Maushold', type: '	normal', rarity: 'uncommon' },
    { num: 231, name: 'Squawkabilly', type: '	normal', rarity: 'uncommon' },
    { num: 232, name: 'Arven', type: '	normal', rarity: 'uncommon' },
    { num: 233, name: 'Cynthia', type: '	normal', rarity: 'uncommon' },
    { num: 234, name: 'Ethan', type: '	normal', rarity: 'uncommon' },
    { num: 235, name: 'Giovanni', type: '	normal', rarity: 'uncommon' },
    { num: 236, name: 'Marnie', type: '	normal', rarity: 'uncommon' },
    { num: 237, name: 'Misty', type: '	normal', rarity: 'uncommon' },
    { num: 238, name: 'Steven', type: '	normal', rarity: 'uncommon' },
    { num: 239, name: 'Antigo Selo Mestre', type: '	normal', rarity: 'uncommon' },
    { num: 240, name: 'Lâmina do Pokémon', type: '	normal', rarity: 'uncommon' },
    { num: 241, name: 'Máquina de Evolução', type: '	normal', rarity: 'uncommon' },
    { num: 242, name: 'Energia Fogo', type: '	normal', rarity: 'uncommon' },
    { num: 243, name: 'Energia Água', type: '	normal', rarity: 'uncommon' },
    { num: 244, name: 'Energia Elétrica', type: '	normal', rarity: 'uncommon' }
  ]
};
