// Dados completos das cartas das coleções SV09 e SV10
// Baseado nos PDFs oficiais da Pokémon TCG

window.pokemonTypes = {
  grass: { name: 'Planta', color: '#5f9e40ff', svg: '<circle cx="12" cy="12" r="10" fill="#78C850"/>'},
  fire: { name: 'Fogo', color: '#d13404ff', svg: '<circle cx="12" cy="12" r="10" fill="#f5761bff"/>'},
  water: { name: 'Água', color: '#4d75d3ff', svg: '<circle cx="12" cy="12" r="10" fill="#7ba3ffff"/>'},
  electric: { name: 'Elétrico', color: '#ffd000ff', svg: '<circle cx="12" cy="12" r="10" fill="#ffe479ff"/>'},
  psychic: { name: 'Psíquico', color: '#9830b8ff', svg: '<circle cx="12" cy="12" r="10" fill="#db7effff"/>'},
  fighting: { name: 'Lutador', color: '#c97200ff', svg: '<circle cx="12" cy="12" r="10" fill="#f0ad56ff"/>'},
  dark: { name: 'Sombrio', color: '#0d2b57ff', svg: '<circle cx="12" cy="12" r="10" fill="#20586eff"/>'},
  steel: { name: 'Aço', color: '#8a8aa5ff', svg: '<circle cx="12" cy="12" r="10" fill="#B8B8D0"/>'},
  dragon: { name: 'Dragão', color: '#a7a266ff', svg: '<circle cx="12" cy="12" r="10" fill="#dae5a6ff"/>'},
  normal: { name: 'Normal', color: '#858585ff', svg: '<circle cx="12" cy="12" r="10" fill="#cececeff"/>'},

  apoiador: { name: 'Apoiador', color: '#db590dff', svg: '<circle cx="12" cy="12" r="10" fill="#f79c68ff"/>'},
  item: { name: 'Item', color: '#037de0ff', svg: '<circle cx="12" cy="12" r="10" fill="#acd2ebff"/>'},
  ferramenta: { name: 'Ferramenta', color: '#702accff', svg: '<circle cx="12" cy="12" r="10" fill="#d6c3f8ff"/>'},
  estadio: { name: 'Estádio', color: '#32c04aff', svg: '<circle cx="12" cy="12" r="10" fill="#b6f0a8ff"/>'},
  energia: { name: 'Energia Especial', color: '#7b6f88ff', svg: '<circle cx="12" cy="12" r="10" fill="#d4cedfff"/>'}
};

window.rarityTypes = {
  common: { name: 'Comum', symbol: '●', color: '#000', bgColor: '#e0e0e0' },
  uncommon: { name: 'Incomum', symbol: '◆', color: '#000', bgColor: '#e0e0e0' },
  rare: { name: 'Rara', symbol: '★', color: '#000', bgColor: '#e0e0e0' },
  doubleRare: { name: 'Rara Dupla', symbol: '★★', color: '#000', bgColor: '#e0e0e0' },
  ultraRare: { name: 'Ultra Rara', symbol: '★★', color: '#ffffffff', bgColor: '#ffc916ff' },
  illustrationRare: { name: 'Ilustração Rara', symbol: '★', color: '#ffffff', bgColor: '#9100e6ff' },
  specialIllustration: { name: 'Ilustração Rara Especial', symbol: '★★', color: '#ffffff', bgColor: '#9100e6ff' },
  hyperRare: { name: 'Hiper Rara', symbol: '★★★', color: '#ffffff', bgColor: '#ffc916ff' }
};

// AMIGOS DE JORNADA
window.cardData = {
  journey: [
    // TIPO PLANTA
    { num: 1, name: 'Caterpie', type: 'grass', rarity: 'common' },
    { num: 2, name: 'Metapod', type: 'grass', rarity: 'common' },
    { num: 3, name: 'Butterfree', type: 'grass', rarity: 'rare' },
    { num: 4, name: 'Paras', type: 'grass', rarity: 'common' },
    { num: 5, name: 'Parasect', type: 'grass', rarity: 'common' },
    { num: 6, name: 'Petilil', type: 'grass', rarity: 'common' },
    { num: 7, name: 'Lilligant', type: 'grass', rarity: 'common' },
    { num: 8, name: 'Maractus', type: 'grass', rarity: 'uncommon' },
    { num: 9, name: 'Karrablast', type: 'grass', rarity: 'common' },
    { num: 10, name: 'Foongus', type: 'grass', rarity: 'common' },
    { num: 11, name: 'Amoonguss ex', type: 'grass', rarity: 'doubleRare' },
    { num: 12, name: 'Shelmet', type: 'grass', rarity: 'common' },
    { num: 13, name: 'Accelgor', type: 'grass', rarity: 'uncommon' },
    { num: 14, name: 'Durant', type: 'grass', rarity: 'common' },
    { num: 15, name: 'Virizion', type: 'grass', rarity: 'uncommon' },
    { num: 16, name: 'Sprigatito', type: 'grass', rarity: 'common' },
    { num: 17, name: 'Floragato', type: 'grass', rarity: 'common' },
    { num: 18, name: 'Meowscarada', type: 'grass', rarity: 'rare' },
    { num: 19, name: 'Nymble', type: 'grass', rarity: 'common' },

    // TIPO FOGO
    { num: 20, name: 'Magmar', type: 'fire', rarity: 'common' },
    { num: 21, name: 'Magmortar', type: 'fire', rarity: 'rare' },
    { num: 22, name: 'Torchic', type: 'fire', rarity: 'common' },
    { num: 23, name: 'Combusken', type: 'fire', rarity: 'uncommon' },
    { num: 24, name: 'Blaziken ex', type: 'fire', rarity: 'doubleRare' },
    { num: 25, name: 'Torkoal', type: 'fire', rarity: 'common' },
    { num: 26, name: 'Darumaka do N', type: 'fire', rarity: 'common' },
    { num: 27, name: 'Darmanitan do N', type: 'fire', rarity: 'uncommon' },
    { num: 28, name: 'Larvesta', type: 'fire', rarity: 'common' },
    { num: 29, name: 'Volcarona', type: 'fire', rarity: 'uncommon' },
    { num: 30, name: 'Reshiram ex', type: 'fire', rarity: 'doubleRare' },
    { num: 31, name: 'Volcanion ex', type: 'fire', rarity: 'doubleRare' },

    // TIPO ÁGUA
    { num: 32, name: 'Articuno', type: 'water', rarity: 'uncommon' },
    { num: 33, name: 'Remoraid', type: 'water', rarity: 'common' },
    { num: 34, name: 'Octillery', type: 'water', rarity: 'uncommon' },
    { num: 35, name: 'Lotad', type: 'water', rarity: 'common' },
    { num: 36, name: 'Lombre', type: 'water', rarity: 'common' },
    { num: 37, name: 'Ludicolo', type: 'water', rarity: 'rare' },
    { num: 38, name: 'Wingull', type: 'water', rarity: 'common' },
    { num: 39, name: 'Pelipper', type: 'water', rarity: 'uncommon' },
    { num: 40, name: 'Wailmer', type: 'water', rarity: 'common' },
    { num: 41, name: 'Wailord', type: 'water', rarity: 'rare' },
    { num: 42, name: 'Regice', type: 'water', rarity: 'uncommon' },
    { num: 43, name: 'Veluza ex', type: 'water', rarity: 'doubleRare' },

    // TIPO ELÉTRICO
    { num: 44, name: 'Geodude de Alola', type: 'electric', rarity: 'common' },
    { num: 45, name: 'Graveler de Alola', type: 'electric', rarity: 'common' },
    { num: 46, name: 'Golem de Alola', type: 'electric', rarity: 'uncommon' },
    { num: 47, name: 'Voltorb da Kisera', type: 'electric', rarity: 'common' },
    { num: 48, name: 'Electrode da Kisera', type: 'electric', rarity: 'uncommon' },
    { num: 49, name: 'Joltik do N', type: 'electric', rarity: 'common' },
    { num: 50, name: 'Togedemaru', type: 'electric', rarity: 'common' },
    { num: 51, name: 'Tapu Koko ex', type: 'electric', rarity: 'doubleRare' },
    { num: 52, name: 'Tadbulb da Kisera', type: 'electric', rarity: 'common' },
    { num: 53, name: 'Bellibolt ex da Kisera', type: 'electric', rarity: 'doubleRare' },
    { num: 54, name: 'Wattrel da Kisera', type: 'electric', rarity: 'common' },
    { num: 55, name: 'Kilowattrel da Kisera', type: 'electric', rarity: 'rare' },

    // TIPO PSÍQUICO
    { num: 56, name: 'Clefairy ex da Lilian', type: 'psychic', rarity: 'doubleRare' },
    { num: 57, name: 'Marowak de Alola', type: 'psychic', rarity: 'uncommon' },
    { num: 58, name: 'Mr. Mime', type: 'psychic', rarity: 'common' },
    { num: 59, name: 'Shuppet', type: 'psychic', rarity: 'common' },
    { num: 60, name: 'Banette', type: 'psychic', rarity: 'uncommon' },
    { num: 61, name: 'Beldum', type: 'psychic', rarity: 'common' },
    { num: 62, name: 'Metang', type: 'psychic', rarity: 'common' },
    { num: 63, name: 'Metagross', type: 'psychic', rarity: 'rare' },
    { num: 64, name: 'Sigilyph do N', type: 'psychic', rarity: 'common' },
    { num: 65, name: 'Oricorio', type: 'psychic', rarity: 'common' },
    { num: 66, name: 'Cutiefly da Lilian', type: 'psychic', rarity: 'common' },
    { num: 67, name: 'Ribombee da Lilian', type: 'psychic', rarity: 'rare' },
    { num: 68, name: 'Comfey da Lilian', type: 'psychic', rarity: 'common' },
    { num: 69, name: 'Mimikyu ex', type: 'psychic', rarity: 'doubleRare' },
    { num: 70, name: 'Dhelmise', type: 'psychic', rarity: 'common' },
    { num: 71, name: 'Impidimp', type: 'psychic', rarity: 'common' },
    { num: 72, name: 'Morgrem', type: 'psychic', rarity: 'common' },
    { num: 73, name: 'Grimmsnarl', type: 'psychic', rarity: 'uncommon' },
    { num: 74, name: 'Milcery', type: 'psychic', rarity: 'common' },
    { num: 75, name: 'Alcremie ex', type: 'psychic', rarity: 'doubleRare' },

    // TIPO LUTADOR
    { num: 76, name: 'Cubone', type: 'fighting', rarity: 'common' },
    { num: 77, name: 'Swinub', type: 'fighting', rarity: 'common' },
    { num: 78, name: 'Piloswine', type: 'fighting', rarity: 'common' },
    { num: 79, name: 'Mamoswine ex', type: 'fighting', rarity: 'doubleRare' },
    { num: 80, name: 'Larvitar', type: 'fighting', rarity: 'common' },
    { num: 81, name: 'Pupitar', type: 'fighting', rarity: 'common' },
    { num: 82, name: 'Regirock', type: 'fighting', rarity: 'rare' },
    { num: 83, name: 'Pancham', type: 'fighting', rarity: 'common' },
    { num: 84, name: 'Rockruff', type: 'fighting', rarity: 'common' },
    { num: 85, name: 'Lycanroc', type: 'fighting', rarity: 'rare' },
    { num: 86, name: 'Silicobra do Lupo', type: 'fighting', rarity: 'common' },
    { num: 87, name: 'Sandaconda do Lupo', type: 'fighting', rarity: 'uncommon' },
    { num: 88, name: 'Toedscool', type: 'fighting', rarity: 'common' },
    { num: 89, name: 'Toedscruel', type: 'fighting', rarity: 'uncommon' },
    { num: 90, name: 'Klawf', type: 'fighting', rarity: 'uncommon' },

    // TIPO SOMBRIO
    { num: 91, name: 'Koffing', type: 'dark', rarity: 'common' },
    { num: 92, name: 'Weezing', type: 'dark', rarity: 'uncommon' },
    { num: 93, name: 'Wooper de Paldea', type: 'dark', rarity: 'common' },
    { num: 94, name: 'Clodsire de Paldea ex', type: 'dark', rarity: 'doubleRare' },
    { num: 95, name: 'Tyranitar', type: 'dark', rarity: 'rare' },
    { num: 96, name: 'Purrloin do N', type: 'dark', rarity: 'common' },
    { num: 97, name: 'Zorua do N', type: 'dark', rarity: 'common' },
    { num: 98, name: 'Zoroark ex do N', type: 'dark', rarity: 'doubleRare' },
    { num: 99, name: 'Pangoro', type: 'dark', rarity: 'uncommon' },
    { num: 100, name: 'Lokix', type: 'dark', rarity: 'uncommon' },
    { num: 101, name: 'Bombirdier', type: 'dark', rarity: 'common' },

    // TIPO AÇO
    { num: 102, name: 'Escavalier', type: 'steel', rarity: 'uncommon' },
    { num: 103, name: 'Klink do N', type: 'steel', rarity: 'common' },
    { num: 104, name: 'Klang do N', type: 'steel', rarity: 'common' },
    { num: 105, name: 'Klinklang do N', type: 'steel', rarity: 'uncommon' },
    { num: 106, name: 'Stunfisk de Galar', type: 'steel', rarity: 'common' },
    { num: 107, name: 'Magearna', type: 'steel', rarity: 'rare' },
    { num: 108, name: 'Corviknight do Lupo', type: 'steel', rarity: 'uncommon' },
    { num: 109, name: 'Cufant', type: 'steel', rarity: 'common' },
    { num: 110, name: 'Copperajah', type: 'steel', rarity: 'uncommon' },
    { num: 111, name: 'Zacian ex do Lupo', type: 'steel', rarity: 'doubleRare' },

    // TIPO DRAGÃO
    { num: 112, name: 'Bagon', type: 'dragon', rarity: 'common' },
    { num: 113, name: 'Shelgon', type: 'dragon', rarity: 'common' },
    { num: 114, name: 'Salamence ex', type: 'dragon', rarity: 'doubleRare' },
    { num: 115, name: 'Druddigon', type: 'dragon', rarity: 'common' },
    { num: 116, name: 'Reshiram do N', type: 'dragon', rarity: 'rare' },

    // TIPO NORMAL 
    { num: 117, name: 'Snorlax do Lupo', type: 'normal', rarity: 'rare' },
    { num: 118, name: 'Sentret', type: 'normal', rarity: 'common' },
    { num: 119, name: 'Furret', type: 'normal', rarity: 'common' },
    { num: 120, name: 'Dunsparce', type: 'normal', rarity: 'common' },
    { num: 121, name: 'Dudunsparce ex', type: 'normal', rarity: 'doubleRare' },
    { num: 122, name: 'Kecleon', type: 'normal', rarity: 'common' },
    { num: 123, name: 'Tropius', type: 'normal', rarity: 'common' },
    { num: 124, name: 'Audino', type: 'normal', rarity: 'common' },
    { num: 125, name: 'Minccino', type: 'normal', rarity: 'common' },
    { num: 126, name: 'Cinccino', type: 'normal', rarity: 'uncommon' },
    { num: 127, name: 'Noibat', type: 'normal', rarity: 'common' },
    { num: 128, name: 'Noivern', type: 'normal', rarity: 'rare' },
    { num: 129, name: 'Komala', type: 'normal', rarity: 'common' },
    { num: 130, name: 'Drampa', type: 'normal', rarity: 'common' },
    { num: 131, name: 'Skwovet', type: 'normal', rarity: 'common' },
    { num: 132, name: 'Greedent', type: 'normal', rarity: 'uncommon' },
    { num: 133, name: 'Rookidee do Lupo', type: 'normal', rarity: 'common' },
    { num: 134, name: 'Corvisquire do Lupo', type: 'normal', rarity: 'common' },
    { num: 135, name: 'Wooloo do Lupo', type: 'normal', rarity: 'common' },
    { num: 136, name: 'Dubwool do Lupo', type: 'normal', rarity: 'rare' },
    { num: 137, name: 'Cramorant', type: 'normal', rarity: 'common' },
    { num: 138, name: 'Cramorant do Lupo', type: 'normal', rarity: 'uncommon' },
    { num: 139, name: 'Lechonk', type: 'normal', rarity: 'common' },
    { num: 140, name: 'Oinkologne', type: 'normal', rarity: 'uncommon' },
    { num: 141, name: 'Squawkabilly', type: 'normal', rarity: 'common' },

    // APOIADOR
    { num: 142, name: 'Abílio e Onara', type: 'apoiador', rarity: 'common' },
    { num: 143, name: 'Treino de Faixa Preta', type: 'apoiador', rarity: 'common' },
    { num: 144, name: 'Treino de Faixa Preta', type: 'apoiador', rarity: 'common' },
    { num: 145, name: 'Treino de Faixa Preta', type: 'apoiador', rarity: 'common' },
    { num: 146, name: 'Busca do Brock', type: 'apoiador', rarity: 'uncommon' },
    { num: 149, name: 'Espírito de Luta da Iris', type: 'apoiador', rarity: 'uncommon' },
    { num: 155, name: 'Pesquisa de Professores', type: 'apoiador', rarity: 'common' },
    { num: 157, name: 'Baderneiro', type: 'apoiador', rarity: 'uncommon' },

    // ITEM 
    { num: 147, name: 'Bolsa do Lupo', type: 'item', rarity: 'uncommon' },
    { num: 153, name: 'PP Up do N', type: 'item', rarity: 'uncommon' },
    { num: 156, name: 'Ingresso Resgatável', type: 'item', rarity: 'uncommon' },
    { num: 158, name: 'Superpoção', type: 'item', rarity: 'uncommon' },

    // FERRAMENTA 
    { num: 148, name: 'Faixa da Escolha do Lupo', type: 'ferramenta', rarity: 'uncommon' },
    { num: 151, name: 'Pérola da Lilian', type: 'ferramenta', rarity: 'uncommon' },

    // ESTÁDIO 
    { num: 150, name: 'Levincia', type: 'estadio', rarity: 'uncommon' },
    { num: 152, name: 'Castelo do N', type: 'estadio', rarity: 'uncommon' },
    { num: 154, name: 'Postwick', type: 'estadio', rarity: 'uncommon' },

    // ENERGIA 
    { num: 159, name: 'Energia Espinhosa', type: 'energia', rarity: 'uncommon' },

    // ILUSTRAÇÃO RARA 
    { num: 160, name: 'Maractus', type: 'grass', rarity: 'illustrationRare' },
    { num: 161, name: 'Articuno', type: 'water', rarity: 'illustrationRare' },
    { num: 162, name: 'Wailord', type: 'water', rarity: 'illustrationRare' },
    { num: 163, name: 'Kilowattrel da Kisera', type: 'electric', rarity: 'illustrationRare' },
    { num: 164, name: 'Ribombee da Lilian', type: 'psychic', rarity: 'illustrationRare' },
    { num: 165, name: 'Swinub', type: 'fighting', rarity: 'illustrationRare' },
    { num: 166, name: 'Lycanroc', type: 'fighting', rarity: 'illustrationRare' },
    { num: 167, name: 'Reshiram do N', type: 'dragon', rarity: 'illustrationRare' },
    { num: 168, name: 'Furret', type: 'normal', rarity: 'illustrationRare' },
    { num: 169, name: 'Noibat', type: 'normal', rarity: 'illustrationRare' },
    { num: 170, name: 'Wooloo do Lupo', type: 'normal', rarity: 'illustrationRare' },

    // ULTRA RARA 
    { num: 171, name: 'Volcanion ex', type: 'fire', rarity: 'ultraRare' },
    { num: 172, name: 'Bellibolt ex da Kisera', type: 'electric', rarity: 'ultraRare' },
    { num: 173, name: 'Clefairy ex da Lilian', type: 'psychic', rarity: 'ultraRare' },
    { num: 174, name: 'Mamoswine ex', type: 'fighting', rarity: 'ultraRare' },
    { num: 175, name: 'Zoroark ex do N', type: 'dark', rarity: 'ultraRare' },
    { num: 176, name: 'Zacian ex do Lupo', type: 'steel', rarity: 'ultraRare' },
    { num: 177, name: 'Salamence ex', type: 'dragon', rarity: 'ultraRare' },
    { num: 178, name: 'Dudunsparce ex', type: 'normal', rarity: 'ultraRare' },
    { num: 179, name: 'Busca do Brock', type: 'apoiador', rarity: 'ultraRare' },
    { num: 180, name: 'Espírito de Luta da Iris', type: 'apoiador', rarity: 'ultraRare' },
    { num: 181, name: 'Baderneiro', type: 'apoiador', rarity: 'ultraRare' },

    // ILUSTRAÇÃO RARA ESPECIAL
    { num: 182, name: 'Volcanion ex', type: 'fire', rarity: 'specialIllustration' },
    { num: 183, name: 'Bellibolt ex da Kisera', type: 'electric', rarity: 'specialIllustration' },
    { num: 184, name: 'Clefairy ex da Lilian', type: 'psychic', rarity: 'specialIllustration' },
    { num: 185, name: 'Zoroark ex do N', type: 'dark', rarity: 'specialIllustration' },
    { num: 186, name: 'Zacian ex do Lupo', type: 'steel', rarity: 'specialIllustration' },
    { num: 187, name: 'Salamence ex', type: 'dragon', rarity: 'specialIllustration' },

    // HIPER RARA 
    { num: 188, name: 'Bellibolt ex da Kisera', type: 'electric', rarity: 'hyperRare' },
    { num: 189, name: 'Zoroark ex do N', type: 'dark', rarity: 'hyperRare' },
    { num: 190, name: 'Energia Espinhosa', type: 'energia', rarity: 'hyperRare' }
  ],



  // RIVAIS PREDESTINADOS 
  rivals: [
    // TIPO PLANTA 
    { num: 1, name: 'Pinsir do Ethan', type: 'grass', rarity: 'uncommon' },
    { num: 2, name: 'Yanma', type: 'grass', rarity: 'common' },
    { num: 3, name: 'Yanmega ex', type: 'grass', rarity: 'doubleRare' },
    { num: 4, name: 'Pineco', type: 'grass', rarity: 'common' },
    { num: 5, name: 'Shroomish', type: 'grass', rarity: 'common' },
    { num: 6, name: 'Breloom', type: 'grass', rarity: 'common' },
    { num: 7, name: 'Roselia da Cintia', type: 'grass', rarity: 'common' },
    { num: 8, name: 'Roserade da Cintia', type: 'grass', rarity: 'rare' },
    { num: 9, name: 'Rotom Corte', type: 'grass', rarity: 'common' },
    { num: 10, name: 'Shaymin', type: 'grass', rarity: 'uncommon' },
    { num: 11, name: 'Dwebble', type: 'grass', rarity: 'common' },
    { num: 12, name: 'Crustle', type: 'grass', rarity: 'rare' },
    { num: 13, name: 'Fomantis', type: 'grass', rarity: 'common' },
    { num: 14, name: 'Lurantis', type: 'grass', rarity: 'uncommon' },
    { num: 15, name: 'Blipbug da Equipe Rocket', type: 'grass', rarity: 'common' },
    { num: 16, name: 'Applin', type: 'grass', rarity: 'common' },
    { num: 17, name: 'Dipplin', type: 'grass', rarity: 'common' },
    { num: 18, name: 'Hydrapple', type: 'grass', rarity: 'rare' },
    { num: 19, name: 'Tarountula da Equipe Rocket', type: 'grass', rarity: 'common' },
    { num: 20, name: 'Spidops da Equipe Rocket', type: 'grass', rarity: 'rare' },
    { num: 21, name: 'Smoliv', type: 'grass', rarity: 'common' },
    { num: 22, name: 'Dolliv', type: 'grass', rarity: 'common' },
    { num: 23, name: 'Arboliva ex', type: 'grass', rarity: 'doubleRare' },
    { num: 24, name: 'Rellor', type: 'grass', rarity: 'common' },
    { num: 25, name: 'Rabsca ex', type: 'grass', rarity: 'doubleRare' },
    { num: 26, name: 'Ogerpon', type: 'grass', rarity: 'uncommon' },

    // TIPO FOGO
    { num: 27, name: 'Growlithe', type: 'fire', rarity: 'common' },
    { num: 28, name: 'Arcanine', type: 'fire', rarity: 'uncommon' },
    { num: 29, name: 'Ponyta', type: 'fire', rarity: 'common' },
    { num: 30, name: 'Rapidash', type: 'fire', rarity: 'uncommon' },
    { num: 31, name: 'Moltres ex da Equipe Rocket', type: 'fire', rarity: 'doubleRare' },
    { num: 32, name: 'Cyndaquil do Ethan', type: 'fire', rarity: 'common' },
    { num: 33, name: 'Quilava do Ethan', type: 'fire', rarity: 'common' },
    { num: 34, name: 'Typhlosion do Ethan', type: 'fire', rarity: 'rare' },
    { num: 35, name: 'Slugma do Ethan', type: 'fire', rarity: 'common' },
    { num: 36, name: 'Magcargo do Ethan', type: 'fire', rarity: 'rare' },
    { num: 37, name: 'Houndour da Equipe Rocket', type: 'fire', rarity: 'common' },
    { num: 38, name: 'Houndoom da Equipe Rocket', type: 'fire', rarity: 'uncommon' },
    { num: 39, name: 'Ho-Oh ex', type: 'fire', rarity: 'doubleRare' },
    { num: 40, name: 'Torchic', type: 'fire', rarity: 'common' },
    { num: 41, name: 'Combusken', type: 'fire', rarity: 'common' },
    { num: 42, name: 'Blaziken', type: 'fire', rarity: 'rare' },
    { num: 43, name: 'Rotom Calor', type: 'fire', rarity: 'common' },
    { num: 44, name: 'Ogerpon', type: 'fire', rarity: 'uncommon' },

    // TIPO ÁGUA
    { num: 45, name: 'Psyduck da Misty', type: 'water', rarity: 'uncommon' },
    { num: 46, name: 'Staryu da Misty', type: 'water', rarity: 'common' },
    { num: 47, name: 'Starmie da Misty', type: 'water', rarity: 'uncommon' },
    { num: 48, name: 'Magikarp da Misty', type: 'water', rarity: 'uncommon' },
    { num: 49, name: 'Gyarados da Misty', type: 'water', rarity: 'rare' },
    { num: 50, name: 'Lapras da Misty', type: 'water', rarity: 'common' },
    { num: 51, name: 'Articuno da Equipe Rocket', type: 'water', rarity: 'rare' },
    { num: 52, name: 'Feebas da Cintia', type: 'water', rarity: 'common' },
    { num: 53, name: 'Milotic da Cintia', type: 'water', rarity: 'uncommon' },
    { num: 54, name: 'Clamperl', type: 'water', rarity: 'common' },
    { num: 55, name: 'Huntail', type: 'water', rarity: 'uncommon' },
    { num: 56, name: 'Gorebyss', type: 'water', rarity: 'rare' },
    { num: 57, name: 'Buizel', type: 'water', rarity: 'common' },
    { num: 58, name: 'Floatzel', type: 'water', rarity: 'uncommon' },
    { num: 59, name: 'Snover', type: 'water', rarity: 'common' },
    { num: 60, name: 'Abomasnow', type: 'water', rarity: 'uncommon' },
    { num: 61, name: 'Rotom Lavagem', type: 'water', rarity: 'common' },
    { num: 62, name: 'Arrokuda', type: 'water', rarity: 'uncommon' },
    { num: 63, name: 'Barraskewda', type: 'water', rarity: 'uncommon' },
    { num: 64, name: 'Cetoddle', type: 'water', rarity: 'common' },
    { num: 65, name: 'Cetitan ex ', type: 'water', rarity: 'doubleRaren' },
    { num: 66, name: 'Dondozo ex', type: 'water', rarity: 'doubleRare' },
    { num: 67, name: 'Ogerpon', type: 'water', rarity: 'uncommon' },

    // TIPO ELÉTRICO
    { num: 68, name: 'Electabuzz', type: 'electric', rarity: 'common' },
    { num: 69, name: 'Electivire ex', type: 'electric', rarity: 'doubleRare' },
    { num: 70, name: 'Zapdos da Equpe Rocket', type: 'electric', rarity: 'rare' },
    { num: 71, name: 'Pichu do Ethan', type: 'electric', rarity: 'common' },
    { num: 72, name: 'Mareep da Equipe Rocket', type: 'electric', rarity: 'common' },
    { num: 73, name: 'Flaaffy da Equipe Rocket', type: 'electric', rarity: 'common' },
    { num: 74, name: 'Ampharos da Equipe Rocket', type: 'electric', rarity: 'uncommon' },
    { num: 75, name: 'Electrike', type: 'electric', rarity: 'common' },
    { num: 76, name: 'Manectric', type: 'electric', rarity: 'uncommon' },
    { num: 77, name: 'Rotom', type: 'electric', rarity: 'common' },
    { num: 78, name: 'Zeraora', type: 'electric', rarity: 'rare' },

    // TIPO PSÍQUICO 
    { num: 79, name: 'Drowzee da Equipe Rocket', type: 'psychic', rarity: 'common' },
    { num: 80, name: 'Hypno da Equipe Rocket', type: 'psychic', rarity: 'uncommon' },
    { num: 81, name: 'Mewtwo ex da Equipe Rocket', type: 'psychic', rarity: 'doubleRare' },
    { num: 82, name: 'Wobbuffet da Equipe Rocket', type: 'psychic', rarity: 'rare' },
    { num: 83, name: 'Baltoy do Steven', type: 'psychic', rarity: 'common' },
    { num: 84, name: 'Claydol do Steven', type: 'psychic', rarity: 'uncommon' },
    { num: 85, name: 'Chingling da Equipe Rocket', type: 'psychic', rarity: 'common' },
    { num: 86, name: 'Carbink do Steven', type: 'psychic', rarity: 'common' },
    { num: 87, name: 'Mimikyu da Equipe Rocket', type: 'psychic', rarity: 'uncommon' },
    { num: 88, name: 'Dottler da Equipe Rocket', type: 'psychic', rarity: 'common' },
    { num: 89, name: 'Orbeetle da Equipe Rocket', type: 'psychic', rarity: 'uncommon' },

    // TIPO LUTADOR
    { num: 90, name: 'Mankey', type: 'fighting', rarity: 'common' },
    { num: 91, name: 'Primeape', type: 'fighting', rarity: 'common' },
    { num: 92, name: 'Annihilape', type: 'fighting', rarity: 'rare' },
    { num: 93, name: 'Sudowoodo do Ethan', type: 'fighting', rarity: 'common' },
    { num: 94, name: 'Larvitar da Equipe Rocket', type: 'fighting', rarity: 'common' },
    { num: 95, name: 'Pupitar da Equipe Rocket', type: 'fighting', rarity: 'common' },
    { num: 96, name: 'Tyranitar da Equipe Rocket', type: 'fighting', rarity: 'rare' },
    { num: 97, name: 'Nosepass', type: 'fighting', rarity: 'common' },
    { num: 98, name: 'Probopass', type: 'fighting', rarity: 'uncommon' },
    { num: 99, name: 'Meditite', type: 'fighting', rarity: 'common' },
    { num: 100, name: 'Medicham', type: 'fighting', rarity: 'uncommon' },
    { num: 101, name: 'Regirock ex', type: 'fighting', rarity: 'doubleRare' },
    { num: 102, name: 'Gible da Cintia', type: 'fighting', rarity: 'common' },
    { num: 103, name: 'Gabite da Cintia', type: 'fighting', rarity: 'common' },
    { num: 104, name: 'Garchomp ex da Cintia', type: 'fighting', rarity: 'doubleRare' },
    { num: 105, name: 'Hippopotas', type: 'fighting', rarity: 'common' },
    { num: 106, name: 'Hippowdon', type: 'fighting', rarity: 'uncommon' },
    { num: 107, name: 'Mudbray', type: 'fighting', rarity: 'common' },
    { num: 108, name: 'Mudsdale', type: 'fighting', rarity: 'uncommon' },
    { num: 109, name: 'Toedscool do Arven', type: 'fighting', rarity: 'common' },
    { num: 110, name: 'Toedscruel do Arven', type: 'fighting', rarity: 'uncommon' },
    { num: 111, name: 'Orgepon', type: 'fighting', rarity: 'uncommon' },

    // TIPO SOMBRIO
    { num: 112, name: 'Ekans da Equipe Rocket', type: 'dark', rarity: 'common' },
    { num: 113, name: 'Arbok da Equipe Rocket', type: 'dark', rarity: 'uncommon' },
    { num: 114, name: 'Nidoran da Equipe Rocket', type: 'dark', rarity: 'common' },
    { num: 115, name: 'Nidorina da Equipe Rocket', type: 'dark', rarity: 'common' },
    { num: 116, name: 'Nidoqueen da Equipe Rocket', type: 'dark', rarity: 'uncommon' },
    { num: 117, name: 'Nidoran da Equipe Rocket', type: 'dark', rarity: 'common' },
    { num: 118, name: 'Nidorino da Equipe Rocket', type: 'dark', rarity: 'common' },
    { num: 119, name: 'Nidoking ex da Equipe Rocket', type: 'dark', rarity: 'doubleRare' },
    { num: 120, name: 'Zubat da Equipe Rocket', type: 'dark', rarity: 'common' },
    { num: 121, name: 'Golbat da Equipe Rocket', type: 'dark', rarity: 'uncommon' },
    { num: 122, name: 'Crobat ex da Equipe Rocket', type: 'dark', rarity: 'doubleRare' },
    { num: 123, name: 'Grimer da Equipe Rocket', type: 'dark', rarity: 'common' },
    { num: 124, name: 'Muk da Equipe Rocket', type: 'dark', rarity: 'uncommon' },
    { num: 125, name: 'Kofffing da Equipe Rocket', type: 'dark', rarity: 'common' },
    { num: 126, name: 'Weezing da Equipe Rocket', type: 'dark', rarity: 'uncommon' },
    { num: 127, name: 'Murkrow da Equipe Rocket', type: 'dark', rarity: 'uncommon' },
    { num: 128, name: 'Sneasel da Equipe Rocket', type: 'dark', rarity: 'rare' },
    { num: 129, name: 'Spiritomb da Cintia', type: 'dark', rarity: 'uncommon' },
    { num: 130, name: 'Purrloin da Marine', type: 'dark', rarity: 'common' },
    { num: 131, name: 'Liepard da Marine', type: 'dark', rarity: 'uncommon' },
    { num: 132, name: 'Scraggy da Marine', type: 'dark', rarity: 'common' },
    { num: 133, name: 'Scrafty da Marine', type: 'dark', rarity: 'uncommon' },
    { num: 134, name: 'Impidimp da Marine', type: 'dark', rarity: 'common' },
    { num: 135, name: 'Morgrem da Marine', type: 'dark', rarity: 'uncommon' },
    { num: 136, name: 'Grimmsnarl ex da Marine', type: 'dark', rarity: 'doubleRare' },
    { num: 137, name: 'Morpeko da Marine', type: 'dark', rarity: 'common' },
    { num: 138, name: 'Maschiff do Arven', type: 'dark', rarity: 'common' },
    { num: 139, name: 'Mabosstiff ex do Arven', type: 'dark', rarity: 'doubleRare' },

    // TIPO AÇO 
    { num: 140, name: 'Forretress', type: 'steel', rarity: 'uncommon' },
    { num: 141, name: 'Skarmory', type: 'steel', rarity: 'common' },
    { num: 142, name: 'Skarmory do Steven', type: 'steel', rarity: 'common' },
    { num: 143, name: 'Beldum do Steven', type: 'steel', rarity: 'common' },
    { num: 144, name: 'Metang do Steven', type: 'steel', rarity: 'uncommon' },
    { num: 145, name: 'Metagross ex do Steven', type: 'steel', rarity: 'doubleRare' },
    { num: 146, name: 'Zamazenta', type: 'steel', rarity: 'rare' },

    // TIPO NORMAL 
    { num: 147, name: 'Rattata da Equipe Rocket', type: 'normal', rarity: 'common' },
    { num: 148, name: 'Raticate da Equipe Rocket', type: 'normal', rarity: 'common' },
    { num: 149, name: 'Meowth da Equipe Rocket', type: 'normal', rarity: 'common' },
    { num: 150, name: 'Persian ex da Equipe Rocket', type: 'normal', rarity: 'doubleRare' },
    { num: 151, name: 'Kangaskhan', type: 'normal', rarity: 'common' },
    { num: 152, name: 'Tauros', type: 'normal', rarity: 'common' },
    { num: 153, name: 'Porygon da Equipe Rocket', type: 'normal', rarity: 'common' },
    { num: 154, name: 'Porygon2 da Equipe Rocket', type: 'normal', rarity: 'common' },
    { num: 155, name: 'Porygon-Z da Equipe Rocket', type: 'normal', rarity: 'uncommon' },
    { num: 156, name: 'Taillow', type: 'normal', rarity: 'common' },
    { num: 157, name: 'Swellow', type: 'normal', rarity: 'common' },
    { num: 158, name: 'Skwovet do Arven', type: 'normal', rarity: 'common' },
    { num: 159, name: 'Greedent do Arven', type: 'normal', rarity: 'rare' },
    { num: 160, name: 'Squawkabilly', type: 'normal', rarity: 'common' },

    // ITEM 
    { num: 161, name: 'Sanduíche do Arven', type: 'item', rarity: 'uncommon' },
    { num: 164, name: 'Reciclador de Energia', type: 'item', rarity: 'uncommon' },
    { num: 168, name: 'Cinza Sagrada', type: 'item', rarity: 'uncommon' },
    { num: 172, name: 'Azucrinabot da Equipe Rocket', type: 'item', rarity: 'uncommon' },
    { num: 175, name: 'Grande Bola da equipe Rocket', type: 'item', rarity: 'uncommon' },
    { num: 178, name: 'Transmissor da Equipe Rocket', type: 'item', rarity: 'uncommon' },
    { num: 179, name: 'Bomba de Risco da Equipe Rocket', type: 'item', rarity: 'uncommon' },
    { num: 181, name: 'Máquina de MT', type: 'item', rarity: 'uncommon' },

    // FERRAMENTA 
    { num: 162, name: 'Peso de Poder da Cíntia', type: 'ferramenta', rarity: 'uncommon' },

    // APOIADOR 
    { num: 163, name: 'Hype da Emcee', type: 'apoiador', rarity: 'common' },
    { num: 165, name: 'Aventura do Ethan', type: 'apoiador', rarity: 'uncommon' },
    { num: 167, name: 'Juiz', type: 'apoiador', rarity: 'uncommon' },
    { num: 170, name: 'Apollo da Equipe Rocket', type: 'apoiador', rarity: 'uncommon' },
    { num: 171, name: 'Athena da Equipe Rocket', type: 'apoiador', rarity: 'uncommon' },
    { num: 174, name: 'Giovanni da Equipe Rocket', type: 'apoiador', rarity: 'uncommon' },
    { num: 176, name: 'Petrel da Equipe Rocket', type: 'apoiador', rarity: 'uncommon' },
    { num: 177, name: 'Próton da Equipe Rocket', type: 'apoiador', rarity: 'uncommon' },

    // ESTADIO 
    { num: 166, name: 'Caverna da Granito', type: 'estadio', rarity: 'uncommon' },
    { num: 169, name: 'Ginásio de Spikemuth', type: 'estadio', rarity: 'uncommon' },
    { num: 173, name: 'Fábrica da Equipe Rocket', type: 'estadio', rarity: 'uncommon' },
    { num: 180, name: 'Torre de Vigia da Equipe Rocket', type: 'estadio', rarity: 'uncommon' },

    // ENERGIA ESPECIAL 
    { num: 182, name: 'Energia da Equipe Rocket', type: 'energia', rarity: 'uncommon' },

    // ILUSTRAÇÃO RARA
    { num: 183, name: 'Dratini', type: 'illustrationRare', rarity: 'common' },
    { num: 184, name: 'illustrationRareair', type: 'illustrationRare', rarity: 'uncommon' },
    { num: 185, name: 'illustrationRareite', type: 'illustrationRare', rarity: 'rare' },
    { num: 186, name: 'Bagon da Cynthia', type: 'illustrationRare', rarity: 'common' },
    { num: 187, name: 'Shelgon da Cynthia', type: 'illustrationRare', rarity: 'uncommon' },
    { num: 188, name: 'Garchomp ex da Cynthia', type: 'illustrationRare', rarity: 'ultraRare' },
    { num: 189, name: 'Axew', type: 'illustrationRare', rarity: 'common' },
    { num: 190, name: 'Fraxure', type: 'illustrationRare', rarity: 'uncommon' },
    { num: 191, name: 'Haxorus', type: 'illustrationRare', rarity: 'rare' },
    { num: 192, name: 'Druddigon', type: 'illustrationRare', rarity: 'uncommon' },
    { num: 193, name: 'Goomy', type: 'illustrationRare', rarity: 'common' },
    { num: 194, name: 'Sliggoo', type: 'illustrationRare', rarity: 'uncommon' },
    { num: 195, name: 'Goodra', type: 'illustrationRare', rarity: 'rare' },
    { num: 196, name: 'Noibat', type: 'illustrationRare', rarity: 'common' },
    { num: 197, name: 'Noivern', type: 'illustrationRare', rarity: 'uncommon' },
    { num: 198, name: 'Applin', type: 'illustrationRare', rarity: 'common' },
    { num: 199, name: 'Flapple', type: 'illustrationRare', rarity: 'uncommon' },
    { num: 200, name: 'Frigibax', type: 'illustrationRare', rarity: 'common' },
    { num: 201, name: 'Arctibax', type: 'illustrationRare', rarity: 'uncommon' },
    { num: 202, name: 'Baxcalibur', type: 'illustrationRare', rarity: 'rare' },
    { num: 203, name: 'Ditto', type: 'illustrationRare', rarity: 'uncommon' },
    { num: 204, name: 'Eevee', type: 'illustrationRare', rarity: 'common' },
    { num: 205, name: 'Porygon', type: 'illustrationRare', rarity: 'common' },

    // ULTRA RARA
    { num: 206, name: 'Porygon2', type: 'normal', rarity: 'uncommon' },
    { num: 207, name: 'Porygon-Z', type: 'normal', rarity: 'rare' },
    { num: 208, name: 'Sentret', type: 'normal', rarity: 'common' },
    { num: 209, name: 'Furret', type: 'normal', rarity: 'uncommon' },
    { num: 210, name: 'Hoothoot', type: 'normal', rarity: 'common' },
    { num: 211, name: 'Noctowl', type: 'normal', rarity: 'uncommon' },
    { num: 212, name: 'Togetic da Cynthia', type: 'normal', rarity: 'uncommon' },
    { num: 213, name: 'Togekiss da Cynthia', type: 'normal', rarity: 'rare' },
    { num: 214, name: 'Starly', type: 'normal', rarity: 'common' },
    { num: 215, name: 'Staravia', type: 'normal', rarity: 'uncommon' },
    { num: 216, name: 'Staraptor', type: 'normal', rarity: 'rare' },
    { num: 217, name: 'Bidoof', type: 'normal', rarity: 'common' },
    { num: 218, name: 'Bibarel', type: 'normal', rarity: 'uncommon' },
    { num: 219, name: 'Patrat', type: 'normal', rarity: 'common' },
    { num: 220, name: 'Watchog', type: 'normal', rarity: 'uncommon' },
    { num: 221, name: 'Minccino', type: 'normal', rarity: 'common' },
    { num: 222, name: 'Cinccino', type: 'normal', rarity: 'uncommon' },
    { num: 223, name: 'Rufflet', type: 'normal', rarity: 'common' },
    { num: 224, name: 'Braviary', type: 'normal', rarity: 'uncommon' },
    { num: 225, name: 'Skwovet', type: 'normal', rarity: 'common' },
    { num: 226, name: 'Greedent', type: 'normal', rarity: 'uncommon' },
    { num: 227, name: 'Lechonk', type: 'normal', rarity: 'common' },

    // ILUSTRAÇÃO RARA ESPECIAL
    { num: 228, name: 'Oinkologne', type: 'normal', rarity: 'uncommon' },
    { num: 229, name: 'Tandemaus', type: 'normal', rarity: 'common' },
    { num: 230, name: 'Maushold', type: 'normal', rarity: 'uncommon' },
    { num: 231, name: 'Squawkabilly', type: 'normal', rarity: 'uncommon' },
    { num: 232, name: 'Arven', type: 'normal', rarity: 'uncommon' },
    { num: 233, name: 'Cynthia', type: 'normal', rarity: 'uncommon' },
    { num: 234, name: 'Ethan', type: 'normal', rarity: 'uncommon' },
    { num: 235, name: 'Giovanni', type: 'normal', rarity: 'uncommon' },
    { num: 236, name: 'Marnie', type: 'normal', rarity: 'uncommon' },
    { num: 237, name: 'Misty', type: 'normal', rarity: 'uncommon' },
    { num: 238, name: 'Steven', type: 'normal', rarity: 'uncommon' },

    // HÍPER RARA
    { num: 239, name: 'Antigo Selo Mestre', type: 'normal', rarity: 'uncommon' },
    { num: 240, name: 'Lâmina do Pokémon', type: 'normal', rarity: 'uncommon' },
    { num: 241, name: 'Máquina de Evolução', type: 'normal', rarity: 'uncommon' },
    { num: 242, name: 'Energia Fogo', type: 'normal', rarity: 'uncommon' },
    { num: 243, name: 'Energia Água', type: 'normal', rarity: 'uncommon' },
    { num: 244, name: 'Energia Elétrica', type: 'normal', rarity: 'uncommon' }
  ]
};
